name: Bump Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    # permissions:
    #   contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        id: node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NVMRC }}
          cache: 'yarn'

      - name: Install deps
        run: |
          yarn install

      # - name:  'Automated Version Bump'
      #   id: bump
      #   uses:  'phips28/gh-action-bump-version@v9.1.0'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     version-type:  ${{ inputs.bump }}
      #     tag-prefix:  'v'
      #     skip-tag:  'true'

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        id: bump
        with:
          github-token: ${{ secrets.github_token }}
          create-summary: true
          output-file: 'false'
          skip-on-empty: 'false'
          git-push: 'false'
          config-file-path: './release.config.js'

      - name: Create release
        id: github-release
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: ${{ steps.bump.outputs.tag }}
          tag_name: ${{ steps.bump.outputs.tag }}
          # target_commitish: main
          generate_release_notes: true

      - name: Create pull request
        id: create-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git status
          git push origin main
          gh pr create --base release-dev --title "Bump version ${{ steps.bump.outputs.tag }}" --body "${{ steps.bump.outputs.changelog }}" || echo Done