name: Bump Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Bump version type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    # permissions:
    #   contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name:  'Automated Version Bump'
      #   id: bump
      #   uses:  'phips28/gh-action-bump-version@v9.1.0'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     version-type:  ${{ inputs.bump }}
      #     tag-prefix:  'v'
      #     skip-tag:  'true'

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: "true"
          git-push: false
          create-summary: true
          output-file: 'false'
          skip-on-empty: 'false'

      - name: Create pull request
        id: create-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git status
          git push origin main
          gh pr create --base release-dev --title "Bump version ${{ steps.changelog.outputs.version }}" --body "${{ steps.changelog.outputs.changelog }}" || echo Done